---
# tasks file for shortcuts
#

- name: copying the function ==> "{{ inventory_hostname }}"
  yum:
    name: "{{ item }}"
    state: "installed"
  with_items:
    - ['net-tools','vim','bind-utils','git','wget','unzip','zip']


- name: copying the function ==> "{{ inventory_hostname }}"
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: 'fun.sh' , dest: "/etc/profile.d/fun.sh" }

